version: "3"

services:
    # image project
    app:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '8989:80'
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-10

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel-10

networks:
    laravel-10:
        driver: bridge
